require("tolga.ui.alpha")
require("tolga.ui.nvim-tree")
require("tolga.ui.bufferline")
require("tolga.ui.catppuccin")
require("tolga.ui.lualine")
require("tolga.ui.indent-blankline")
require("tolga.ui.notify")
require("tolga.ui.navic")
